image:
  file: .gitpod.Dockerfile

tasks:
  - name: Soundcheck
    command: aws --version

ports:
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - aws-scripting-guy.cform