version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "url-shortener-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17jyu4x0ty4my"
s3_prefix = "url-shortener-dev"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
