# sam deploy -t 'template.yaml' --stack-name 'shortener-stack' --capabilities CAPABILITY_IAM --resolve-s3
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for url-shortener

Parameters:
  NetworkStackName:
    Type: String
    Description: The name of the network stack
    Default: network-stack

  DatabaseStackName:
    Type: String
    Description: The name of the network stack
    Default: database-stack

Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  FunctionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the function
      VpcId:
        Fn::ImportValue:
          !Sub '${NetworkStackName}:VpcId'

  ShortenerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ShortenerFunction
      Handler: shortener.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref 'FunctionSecurityGroup'
        SubnetIds:
          - Fn::ImportValue:
              !Sub '${NetworkStackName}:PrivateSubnet0'
          - Fn::ImportValue:
              !Sub '${NetworkStackName}:PrivateSubnet1'
          - Fn::ImportValue:
              !Sub '${NetworkStackName}:PrivateSubnet2'

      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USERNAME:
            Fn::ImportValue:
              !Sub '${DatabaseStackName}:DBUsername'
          DB_PASSWORD:
            Fn::ImportValue:
              !Sub '${DatabaseStackName}:DBPassword'
          DB_NAME:
            Fn::ImportValue:
              !Sub '${DatabaseStackName}:DBName'
          DB_ADDRESS:
            Fn::ImportValue:
              !Sub '${DatabaseStackName}:DBAddress'

          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        Shortener:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{path+}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShortenerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ShortenerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShortenerFunction.Arn
  ShortenerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShortenerFunctionRole.Arn
